FROM python:3.10.9-bullseye

WORKDIR ./application

RUN pip install Flask

RUN apt-get update && apt-get install -y python3-pip python3

COPY ./help_text.txt /help_text.txt

COPY ./requirements.txt /application/requirements.txt

RUN pip install -r requirements.txt

COPY ./app.py /app.py


COPY ./wait-for-it.sh /application/wait-for-it.sh

CMD ./wait-for-it.sh mysql:3306 -- python3 app.py
